account/urls.py
from django.urls import path
from account.views import RegistrationView, LoginView, LogoutUserView

app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
]

notes/urls.py
from django.urls import path
from .views import (
    NotesListView,
    NoteUpdateView,
    ArchiveNoteView,
    CategoryListView,
    CategoryUpdateView,
    SearchNoteView,
    FilterNotesView,
    NoteDeleteView,
    NoteUpdateView,
    CategoryDeleteView,
)

urlpatterns = [
    path("", NotesListView.as_view(), name="notes-list"),
    path("category/", CategoryListView.as_view(), name="category"),
    path(
        "category/<int:category_id>",
        CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "category/<int:category_id>/delete",
        CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path("note/<int:note_id>/edit/", NoteUpdateView.as_view(), name="note-update"),
    path("note/<int:note_id>/delete/", NoteDeleteView.as_view(), name="note-delete"),
    path("archive/", ArchiveNoteView.as_view(), name="get-archive"),
    path("archive/<int:note_id>/", ArchiveNoteView.as_view(), name="archive_note"),
    path("search/", SearchNoteView.as_view(), name="search"),
    path("filter/", FilterNotesView.as_view(), name="filter"),
]

notes_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("notes.urls")),
    path("", include("account.urls")),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/archive.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Notes App</title>
  <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>

<body>
<div class="container">
  <div class="header">
    <h1>
      {% if user.is_authenticated %}
        <a style="color: black" href="{% url "notes-list" %}">
          {{ user.get_username|capfirst }}'s notes
        </a>
      {% else %}
        <p>Welcome, new user. Please log in.</p>
      {% endif %}
    </h1>
    <div class="header-bth">
      <button class="save" id="create-category-btn">Create new category</button>
      <button class="save"><a href="{% url "notes-list" %}">Actual notes</a></button>
    </div>
  </div>

  <div class="filter-container">
    <div class="search">
      <img src="{% static "icons/search.svg" %}" alt="search">
      <input type="text" placeholder="type to search...">
    </div>

    <div class="category-selector">
      <select id="category" name="category">
        <option value="personal">Personal</option>
        <option value="work">Work</option>
        <option value="study">Study</option>
        <option value="other">Other</option>
      </select>
    </div>
  </div>
  <h2>Archived notes</h2>
  <div class="notes-list">
    {% for note in notes %}
      <div class="note" style="background-color: {{ note.category.color }};">
        <span>{{ note.text }}</span>
        <div class="note-footer">
          <p>Category: {{ note.category }}</p>
          <div class="note-footer-bth">
            <button onclick="deleteNote({{ note.id }})">
              <img src="{% static "icons/delete.svg" %}" alt="delete">
            </button>
            <button onclick="archiveNote({{ note.id }})">
              <img src="{% static "icons/archive.svg" %}" alt="archive">
            </button>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
<div id="popup-create-category" class="popup-create-category">
  <div class="popup__box">
    <button class="close-category-popup-btn" id="close-popup-create-category">
      <img src="{% static "icons/close.svg" %}" alt="">
    </button>
    <h5 class="category-title">
      Create category
    </h5>
    <div class="popup-body">
      <form id="createCategoryForm" action="{% url "category" %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="categoryName">Category name:</label>
          <input type="text" class="form-control" id="categoryName" name="name">
        </div>
        <div class="form-group">
          <label for="categoryColor">Колір категорії</label>
          <input type="text" class="form-control" id="categoryColor" name="color">
        </div>
        <button type="submit" class="save">Save</button>
      </form>
    </div>
  </div>
</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{% static "js/script.js" %}"></script>
<script>
    function deleteNote(noteId) {
        if (confirm('Are you sure you want to delete this note?')) {
            $.ajax({
                url: '{% url 'note-delete' note_id=999 %}'.replace('999', noteId),
                type: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function (data) {
                    location.reload();
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.error('Error:', errorThrown);
                }
            });
        }
    }

    function archiveNote(noteId) {
        if (confirm('Are you sure you want to archive this note?')) {
            $.ajax({
                url: '{% url 'archive_note' note_id=999 %}'.replace('999', noteId),
                type: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function (data) {
                    location.reload();
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.error('Error:', errorThrown);
                }
            });
        }
    }
</script>


</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Notes App</title>
  <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>

<body>
<div class="container">
  <div class="header">
    <h1>
      {% if user.is_authenticated %}
        <a style="color: black" href="{% url "notes-list" %}">
          {{ user.get_username|capfirst }}'s notes
        </a>
      {% else %}
        <p>Welcome, new user. Please log in.</p>
      {% endif %}
    </h1>
    <div class="header-bth">
      <button class="save" id="create-category-btn">Create new category</button>
      <button class="save"><a style="color: black; font-size: 18px;" href="{% url "get-archive" %}">Archive</a></button>
      {% if user.is_authenticated %}
        <burron class="save"><a style="color: black; font-size: 18px;" href="{% url "account:logout" %}">Log Out</a>
        </burron>
      {% endif %}
    </div>
  </div>
  {% block content %}

  {% endblock content %}
  <div id="popup-create-category" class="popup-create-category">
    <div class="popup__box">
      <button class="close-category-popup-btn" id="close-popup-create-category">
        <img src="{% static "icons/close.svg" %}" alt="">
      </button>
      <h3 class="popup-category-title">
        Create category
      </h3>
      <div class="popup-body">
        <form id="createCategoryForm" action="{% url "category" %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label class="category-field__label" for="categoryName">Category name:</label>
            <input class="category-field__input" type="text" id="categoryName" name="name">
          </div>
          <div class="form-group">
            <label for="color-picker">Color:</label>
            <div class="color-picker">
              <input type="hidden" id="color" name="color">
              <div class="color" style="background-color: #cfe027;" data-color="#ff0000"></div>
              <div class="color" style="background-color: rgba(5,115,5,0.62);" data-color="#00ff00"></div>
              <div class="color" style="background-color: #3232ff;" data-color="#0000ff"></div>
              <div class="color" style="background-color: #6804bb;" data-color="#ffff00"></div>
              <div class="color" style="background-color: #00ffff;" data-color="#00ffff"></div>
            </div>
          </div>
          <button type="submit" class="category-save-btn">Save</button>
        </form>
      </div>
    </div>
  </div>
</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{% static "js/script.js" %}"></script>
<script>
    function deleteNote(noteId) {
        if (confirm('Are you sure you want to delete this note?')) {
            $.ajax({
                url: '{% url 'note-delete' note_id=999 %}'.replace('999', noteId),
                type: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function (data) {
                    location.reload();
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.error('Error:', errorThrown);
                }
            });
        }
    }

    function archiveNote(noteId) {
        if (confirm('Are you sure you want to archive this note?')) {
            $.ajax({
                url: '{% url 'archive_note' note_id=999 %}'.replace('999', noteId),
                type: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function (data) {
                    location.reload();
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.error('Error:', errorThrown);
                }
            });
        }
    }
</script>
<script>
    $(document).ready(function () {
        filterSelection('all');
    });

    function filterSelection(category) {


        $.ajax({
            type: "GET",
            url: "filter/",
            data: {
                category: category

            },
            success: function (data) {
                $("#notesContainer").html(data);
            },
            error: function (xhr, textStatus, errorThrown) {
                console.log("Error:", errorThrown);
            }
        });
    }
    function orderbySelection() {
        var selectElement = document.getElementById("ordering-notes");
        var selectedValue = selectElement.value;
        console.log(selectedValue)

        $.ajax({
            type: "GET",
            url: "filter/",
            data: {
                order_by: selectedValue
            },
            success: function (data) {
                $("#notesContainer").html(data);
            },
            error: function (xhr, textStatus, errorThrown) {
                console.log("Error:", errorThrown);
            }
        });
    }
</script>
</html>

templates/category_edit.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Category</title>
</head>
<body>
    <h1>Edit Category</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

templates/filter_node.html
{% load static %}
<div class="notes-list">
  <form class="note new" method="post" action="{% url "notes-list" %}">
    {% csrf_token %}
    <textarea name="text" rows="8" cols="10" placeholder="Type to add a note..."></textarea>
    <div class="note-footer">
      <div class="category-selector">
        <label class="category-label" for="category">Category</label>
        <select name="category">
          {% for category in categories %}
            <option value="{{ category.name }}">{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="save">Save</button>
    </div>
  </form>
  {% for note in notes %}
    <div class="note" style="background-color: {{ note.category.color }};">
      <span>{{ note.text }}</span>
      <div class="note-footer">
        <p>Category: {{ note.category }}</p>
        <div class="note-footer-bth">
          <button>
            <a href="{% url "note-update" note_id=note.id %}"><img src="{% static "icons/edit.svg" %}" alt=""></a>
          </button>
          <button onclick="deleteNote({{ note.id }})">
            <img src="{% static "icons/delete.svg" %}" alt="delete">
          </button>
          <button onclick="archiveNote({{ note.id }})">
            <img src="{% static "icons/archive.svg" %}" alt="archive">
          </button>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="filter-container">
    <form class="search" action="{% url "search" %}" method="get">
      <img src="{% static "icons/search.svg" %}" alt="search">
      <input autocomplete="off" type="search" name="query" placeholder="type to search...">
    </form>
    <div class="category-selector">
      <select id="ordering-notes" name="order-by" onchange="orderbySelection()">
        <option value="date_created">Дата створення</option>
        <option value="word_count">Кількість слів</option>
        <option value="unique_word_count">Унікальні слова</option>
      </select>
    </div>
  </div>
  <div id="myBtnContainer">
    <button class="btn active" onclick="filterSelection('all')"> Show all</button>
    {% for category in categories %}
      <button class="btn" onclick="filterSelection('{{ category.name }}')"> {{ category.name }}</button>
    {% endfor %}
  </div>
  <h2>Actual notes</h2>
  <div id="notesContainer">
    <!-- Тут буде відображуватися відфільтрована інформація -->
  </div>
  </div>
{#  <div id="popup-create-category" class="popup-create-category">#}
{#    <div class="popup__box">#}
{#      <button class="close-category-popup-btn" id="close-popup-create-category">#}
{#        <img src="{% static "icons/close.svg" %}" alt="">#}
{#      </button>#}
{#      <h3 class="popup-category-title">#}
{#        Create category#}
{#      </h3>#}
{#      <div class="popup-body">#}
{#        <form id="createCategoryForm" action="{% url "category" %}" method="post">#}
{#          {% csrf_token %}#}
{#          <div class="form-group">#}
{#            <label class="category-field__label" for="categoryName">Category name:</label>#}
{#            <input class="category-field__input" type="text" class="form-control" id="categoryName" name="name">#}
{#          </div>#}
{#          <div class="form-group">#}
{#            <label class="category-field__label" for="categoryColor">Category color</label>#}
{#            <input class="category-field__input" type="text" class="form-control" id="categoryColor" name="color">#}
{#          </div>#}
{#          <button type="submit" class="category-save-btn">Save</button>#}
{#        </form>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
  </body>
{% endblock content %}

</html>

templates/note_edit.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Note</title>
</head>
<body>
    <h1>Edit Note</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>